#lang planet neil/sicp
(define (mystery x)
  (define (loop x y)
    (if (null? x)
        y
        (let ((temp (cdr x)))
          (set-cdr! x y)
          (loop temp x))))
  (loop x '()))
(define v (list 'a 'b ))
(define w (mystery v))
(define fuck (cons 'x 'y))
(define shit (cons fuck fuck))
(display shit)
(newline)
(set-cdr! fuck (cons 'z '()))
(display shit)