#lang planet neil/sicp
(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (dispatch message)
      (cond ((eq? 'insert message)
                 (lambda (value)
                   (if (null? front-ptr)
                       (set! front-ptr (cons value '()))
                       (set! front-ptr (append front-ptr (cons value '()))))
                   (set! rear-ptr value)
                   (display front-ptr)))
            ((eq? 'delete message)
             (if (null? front-ptr)
                 (error "DELETE called with an empty queue")
                 (set! front-ptr (cdr front-ptr)))
             (display front-ptr))
            (else 
             (error "Unknown Requeset -- DISPATCH" message))))
    dispatch))
(define q (make-queue))
((q 'insert) 1)
(newline)
((q 'insert) 2)
(newline)
(q 'delete)
(newline)
(q 'delete)